
name: Build and deploy Node.js app to Azure Web App - q-me-lb

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: 'Checkout Master'
      uses: actions/checkout@v2
      with:
        path: master

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present
    
    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with:
        app-name: q-me-lb
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
        package: .
